default_platform(:android)

platform :android do

  lane :runUnitTest do
    gradle(task:"test")
  end

  lane :runClean do
    gradle(task:"clean")
  end

  lane :runInstrumentedTest do
    build_android_app(
          task: 'assemble',
          build_type: 'Debug'
        )
    build_android_app(
          task: 'assemble',
          build_type: 'AndroidTest'
        )
    screengrab()
  end

  lane :runBuildApk do
    gradle(task:"assembleDebug")
  end

  ######## FIREBASE DISTRIBUTION  ########
    desc "Submit a new Google Test Build to Firebase App Distribution"
    lane :distribute do
            build_android_app(task:"clean assembleDebug")
            # build_android_app is a built-in fastlane action.
            release = firebase_app_distribution(
                app: "1:494322602035:android:66a12a4f12882fc5b51346",
                testers: "tester1@company.com",
                firebase_cli_token: "1//0gXzTe4HPRLzKCgYIARAAGBASNwF-L9IraYJ_vq-kj3PzwT_xQZIK-GVERR_NgMboqL-N8R2mE710hdR3RTWhOKLVGJ7DDcoWQvE",
                release_notes: "Lots of amazing new features to test out!"
            )
    end

end