default_platform(:android)

platform :android do

  lane :runUnitTest do
    gradle(task:"test")
  end

  lane :runClean do
    gradle(task:"clean")
  end

  lane :runInstrumentedTest do
    gradle(tasks:"connectedAndroidTest")
    bat env.ADB + ' install -r ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk'
    bat env.ADB + ' install -r ./app/build/outputs/apk/debug/app-debug.apk'
    bat env.ADB + ' devices'
    bat env.ADB + ' shell am instrument -w com.academy.alfagiftmini.test/androidx.test.runner.AndroidJUnitRunner'

#     build_android_app(
#           task: 'assemble',
#           build_type: 'Debug'
#         )
#     build_android_app(
#           task: 'assemble',
#           build_type: 'AndroidTest'
#         )
#     screengrab()
  end

  lane :runBuildApk do
    gradle(task:"assembleDebug")
  end

  ######## FIREBASE DISTRIBUTION  ########
    desc "Submit a new Google Test Build to Firebase App Distribution"
    lane :distribute do
            build_android_app(task:"clean assembleDebug")
            # build_android_app is a built-in fastlane action.
            release = firebase_app_distribution(
                app: "1:494322602035:android:66a12a4f12882fc5b51346",
                testers: "tester1@company.com",
                service_credentials_file: "fastlane/firebase_credentials.json",
                release_notes: "Lots of amazing new features to test out!"
            )
    end

end